### PR TITLE
update JSON output

### PR DESCRIPTION
**Pull request by ukos-git**
This change introduces proper JSON file output that can be used as input to plotly generators i.e. in python (example provided in bin/).

Previously, a JSON code for the plotly server communication was created. As @alexcjohnson mentioned, plotly is now Open Source. Server communication has become optional. There are better programs to do that than Igor Pro.

The goal of this library therefore changed to providing an interface between Igor Pro graphs and Plotly JSON format. Uploading the files to plot.ly should be handled by other plot.ly implementations.

This PR also fixes some major Coding inconsistencies, cleanup, wording, white space errors etc. Code is not in a perfect state but mostly cleaner.

### CODE REVIEW

**Comment by ukos-git** [comment]
@alexcjohnson @t-b someone with a little Igor Pro experience to give a review?

The repo was in a really bad condition. Changes to review are mostly in ab0d916

**Comment by alexcjohnson** [comment]
@ukos-git my Igor is too rusty to review but overall I think this looks great!

I'm not sure if there's anyone using this package to push graphs to Plotly cloud, but just in case, I wonder if it would make sense to have a second file something like `PlotlyCloud.ipf` that includes only this piece? That way users who don't need this would only install `PlotlyFunctions.ipf`, and would not need `easyHTTP`, but if anyone does want it they could still do it by installing both files and `easyHTTP`.

**Comment by t-b** [comment]
@alexcjohnson FYI: IP7 and above has `UrlRequest` which should replace all common use cases of `easyHTTP`.

**Comment by ukos-git** [comment]
Why should we bother with the JSON upload functions if python is doing such a good job for this. Better keep one functionality at a time. I agree that output to plot.ly should be implemented but a the same time also updates to a local UI should be possible. No need to transfer all the data on default over the web to plot.ly and do user authentification with fixed jbmiller strings etc. Let's let python apps do the transfer and output only the JSON representation within igor pro.

**Comment by alexcjohnson** [comment]
My thought was that it’s not a lot of code to carry around (presumably even less with `UrlRequest`), and for use cases that do not already involve any Python this may be a substantial simplification. But I will defer to you two, I don’t speak on behalf of any specific users.

**Comment by t-b** [comment]
@ukos-git A standalone IP solution would be nice to have though.

**Comment by ukos-git** [comment]
I guess you are right but the last implementation with plain passwords written in the code did not look very professional to me.

I will include the credentials as follows:

# store credentials in PackagePrefs

Storing in PackagePrefs is preferred over storing in the experiment if the expriment file is shared among users with different credentials.

similar syntax to python:

```python
import plotly 
plotly.tools.set_credentials_file(username='DemoAccount', api_key='lr1c37zw81')
```

username and api_key are stored plain. I have to reserve a fixed amount of space for username and api_key, but I don't know the max length. I will probably assume strlen(api_key) == 20 and  strlen(username) == 50

# API communication

* re-add parameter `skipSend` and set the default mode back to sending
* use UrlRequest for API calls
* Assume the following syntax for API calls:

  * target URL: `"http://plot.ly/clientresp"`
  * printf "un=%s&key=%s&platform=IgorPro&args=", $username, $api_key
  * args += $JSON_DUMP

**Comment by alexcjohnson** [comment]
> did not look very professional to me.

I cannot disagree 😏 your implementation sounds great.

**Comment by ukos-git** [comment]
I cannot get the api call right. I am sending

```igorpro
string apicall = "un=username&key=api_keys&platform=IgorPro&origin=plot&kwargs={\"fileopt\":\"overwrite\"}&args={\"data\":[{\"y\":[20,14,23],\"type\":\"bar\"}]}"
```

via POST to `http://plot.ly/clientresp` which gives a human readable error page with an image stating

>       Uh oh. An error occurred while loading this page.

The original code put layout under kwargs etc but I send the data/layout object under normal args as this is the syntax everywhere else.

Can someone point me to the API description?

**Comment by ukos-git** [comment]
I pushed the latest changes. With kwargs setting the plot name, I now get a proper JSON error message:

```igorpro
PlotlyTestConnection()
  {"error": "Uh oh, an error occurred on the server. ", "warning": "", "message": "", "url": "", "filename": ""}
```

**Comment by alexcjohnson** [comment]
Alright, the story is a bit more complicated... the old implementation is using `plot.ly/clientresp`, which does still work but we're trying to get rid of it.

Unfortunately the replacement "V2" API requires you to explicitly separate data from the plot definition. This has various advantages, like you can update a graph's style without changing the data, or use the same data for multiple graphs, but it's a good deal more complicated to use - you have to (1) split the data out from the graph, (2) send that data to the server as "grid" and wait for the response, (3) insert grid references back in the graph JSON, (4) send the new graph JSON to the server.

So, all that said... it's going to be a bigger project, perhaps in the end it *is* better to remove this functionality until there's a specific need for it.

Here's a starting point for how plotly.py handles this: https://github.com/plotly/plotly.py/blob/3678aa925489b9ed429dc28863040dbb391dadb1/chart_studio/api/v2/plots.py

**Comment by alexcjohnson** [comment]
Here's the full V2 API reference in case you do decide it's worthwhile https://api.plot.ly/v2/

**Comment by ukos-git** [comment]
Ok. Thank you all for the feedback. I restored the legacy API by splitting up layout and data generation. I did not make it any further.

The purpose of this PR was to add json output to a file, rework the Code (even though there is still work left), Remove the XOP dependencie and get it installed quicker.

I have also rewritten the Readme.md and added a new example plot :-)

**Pull request merged**
